// src/components/ChatInput.vue
<script setup lang="ts">
import { ref, watch } from 'vue'

const props = defineProps<{
  loading?: boolean
}>()

const emit = defineEmits<{
  send: [content: string]
}>()

const input = ref('')
const textareaRef = ref<HTMLTextAreaElement>()
const isFocused = ref(false)

function autoResize() {
  const el = textareaRef.value
  if (!el) return
  el.style.height = 'auto'
  el.style.height = Math.min(el.scrollHeight, 160) + 'px'
}

watch(input, autoResize)

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault()
    handleSend()
  }
}

function handleSend() {
  const content = input.value.trim()
  if (!content || props.loading) return
  emit('send', content)
  input.value = ''
  if (textareaRef.value) {
    textareaRef.value.style.height = 'auto'
  }
}
</script>

<template>
  <div class="border-t border-border-default bg-surface-1 p-4">
    <div
      :class="[
        'relative flex items-end gap-2 rounded-xl border bg-surface-2 px-3 py-2.5 transition-all duration-200',
        isFocused
          ? 'border-accent-500/50 shadow-[0_0_0_3px_rgba(59,130,246,0.1)]'
          : 'border-border-default hover:border-border-default/80',
      ]"
    >
      <textarea
        ref="textareaRef"
        v-model="input"
        rows="1"
        class="max-h-40 w-full resize-none bg-transparent text-sm leading-relaxed text-text-primary placeholder-text-tertiary outline-none"
        placeholder="输入问题，Shift + Enter 换行，Enter 发送..."
        :disabled="loading"
        @keydown="handleKeydown"
        @focus="isFocused = true"
        @blur="isFocused = false"
      />

      <button
        :disabled="!input.trim() || loading"
        :class="[
          'flex h-8 w-8 shrink-0 items-center justify-center rounded-lg transition-all duration-200',
          input.trim() && !loading
            ? 'bg-accent-500 text-white shadow-lg shadow-accent-glow hover:bg-accent-400 active:scale-95'
            : 'bg-surface-4 text-text-tertiary',
        ]"
        @click="handleSend"
      >
        <span
          :class="[
            loading ? 'i-mdi-loading animate-spin' : 'i-mdi-send',
            'text-sm',
          ]"
        />
      </button>
    </div>

    <div class="mt-1.5 flex items-center justify-between px-1">
      <p class="text-[11px] text-text-tertiary">
        AI 生成内容仅供参考
      </p>
      <p class="text-[11px] text-text-tertiary">
        {{ input.length }} 字
      </p>
    </div>
  </div>
</template>

// packages/web/src/features/chat/components/ChatInput.tsx
import { useState, useRef, useCallback } from 'react'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { KnowledgeBaseSelector } from './KnowledgeBaseSelector'

interface ChatInputProps {
  onSend: (content: string, knowledgeBaseIds?: string[]) => void
  disabled?: boolean
  placeholder?: string
  isStreaming?: boolean
  onStop?: () => void
}

export function ChatInput({
  onSend,
  disabled = false,
  placeholder = '输入消息...',
  isStreaming = false,
  onStop,
}: ChatInputProps) {
  const [value, setValue] = useState('')
  const [selectedKbIds, setSelectedKbIds] = useState<string[]>([])
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  const handleToggleKb = useCallback((kbId: string) => {
    setSelectedKbIds((prev) =>
      prev.includes(kbId) ? prev.filter((id) => id !== kbId) : [...prev, kbId],
    )
  }, [])

  const handleSend = useCallback(() => {
    const trimmed = value.trim()
    if (!trimmed || disabled || isStreaming) return
    onSend(trimmed, selectedKbIds)
    setValue('')
    textareaRef.current?.focus()
  }, [value, disabled, isStreaming, selectedKbIds, onSend])

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      if (isStreaming) return
      handleSend()
    }
  }

  return (
    <div className="border-t border-border-default bg-surface-1 p-4">
      <div className="mb-2 flex items-center gap-2">
        <KnowledgeBaseSelector
          selectedIds={selectedKbIds}
          onToggle={handleToggleKb}
          disabled={disabled || isStreaming}
        />
        {selectedKbIds.length > 0 && (
          <span className="text-xs text-text-tertiary">已选 {selectedKbIds.length} 个知识库</span>
        )}
      </div>
      <div className="flex items-end gap-2">
        <Textarea
          ref={textareaRef}
          value={value}
          onChange={(e) => setValue(e.target.value)}
          onKeyDown={handleKeyDown}
          disabled={disabled || isStreaming}
          placeholder={placeholder}
          rows={2}
          className="flex-1 resize-none"
        />
        {isStreaming ? (
          <Button variant="destructive" onClick={onStop}>
            停止
          </Button>
        ) : (
          <Button onClick={handleSend} disabled={disabled || !value.trim()}>
            发送
          </Button>
        )}
      </div>
    </div>
  )
}
