// packages/web/src/features/chat/components/ChatMessage.tsx
import type { Message } from '@goferbot/data'
import ReactMarkdown from 'react-markdown'
import { cn } from '@/utils/cn'

interface ChatMessageProps {
  message: Message
}

export function ChatMessage({ message }: ChatMessageProps) {
  const isUser = message.role === 'user'

  return (
    <div className={cn('flex w-full gap-3 px-4 py-3', isUser ? 'justify-end' : 'justify-start')}>
      <div
        className={cn(
          'flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-sm font-medium',
          isUser
            ? 'order-2 bg-brand-primary text-white'
            : 'order-1 bg-surface-3 text-text-secondary',
        )}
      >
        {isUser ? 'U' : 'AI'}
      </div>

      <div
        className={cn(
          'max-w-[75%] rounded-lg px-4 py-3 text-sm leading-relaxed',
          isUser ? 'order-1 bg-brand-primary text-white' : 'order-2 bg-surface-2 text-text-primary',
        )}
      >
        {isUser ? (
          <p>{message.content}</p>
        ) : (
          <div className="prose prose-sm max-w-none prose-headings:text-text-primary prose-p:text-text-primary prose-a:text-brand-primary prose-code:bg-surface-3 prose-code:px-1 prose-code:py-0.5 prose-code:rounded prose-pre:bg-surface-3 prose-pre:text-text-primary">
            <ReactMarkdown>{message.content}</ReactMarkdown>
          </div>
        )}
      </div>
    </div>
  )
}

// packages/webui/src/components/ChatMessage.vue
<script setup lang="ts">
import type { Message } from '@/stores/session'
import { BotIcon, UserIcon } from 'lucide-vue-next'
import MarkdownRender from './MarkdownRender.vue'

defineProps<{
  message: Message
}>()
</script>

<template>
  <div
    data-testid="chat-message"
    :data-role="message.role"
    :class="[
      'flex w-full',
      message.role === 'user' ? 'justify-end' : 'justify-start',
    ]"
  >
    <div class="flex max-w-[85%] gap-3">
      <!-- AI Avatar -->
      <div
        v-if="message.role === 'assistant'"
        class="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-accent-soft"
      >
        <BotIcon class="size-4 text-accent-500" />
      </div>

      <div
        :class="[
          'relative overflow-hidden rounded-2xl px-4 py-3 shadow-xs',
          message.role === 'user'
            ? 'bg-accent-500 text-white'
            : 'border border-border-default bg-white text-text-primary',
        ]"
      >
        <!-- AI message top accent line -->
        <div
          v-if="message.role === 'assistant'"
          class="absolute left-0 top-0 h-full w-[2px] bg-accent-500/40"
        />

        <div v-if="message.role === 'user'" class="whitespace-pre-wrap text-sm leading-relaxed">
          {{ message.content }}
        </div>
        <MarkdownRender v-else :content="message.content" />
      </div>

      <!-- User Avatar -->
      <div
        v-if="message.role === 'user'"
        class="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-surface-2"
      >
        <UserIcon class="size-4 text-text-secondary" />
      </div>
    </div>
  </div>
</template>
