// packages/webui/src/overlays/dialogs/CreateFolderDialog.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog'
import { defineDialog } from '@/overlays/composables/useDialog'

const props = defineProps<{
  kbId: string
  parentFolderId?: string | null
  onConfirm: (name: string) => void | Promise<void>
}>()

const { isOpen, close } = defineDialog()
const name = ref('')
const error = ref('')
const isSubmitting = ref(false)

async function handleConfirm() {
  const trimmed = name.value.trim()
  if (!trimmed) {
    error.value = '请输入文件夹名称'
    return
  }
  isSubmitting.value = true
  try {
    await props.onConfirm(trimmed)
    close()
  } catch (e) {
    error.value = e instanceof Error ? e.message : '创建失败'
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <Dialog :open="isOpen" @update:open="(v) => !v && close()">
    <DialogContent class="w-96">
      <DialogHeader>
        <DialogTitle>新建文件夹</DialogTitle>
      </DialogHeader>
      <div class="space-y-4">
        <Input
          v-model="name"
          type="text"
          placeholder="输入文件夹名称"
          class="rounded-xl border-border-default bg-surface-1 px-3 py-2.5 text-sm focus:border-accent-500/50"
          @keyup.enter="handleConfirm"
        />
        <p v-if="error" class="text-xs text-danger-500">{{ error }}</p>
      </div>
      <DialogFooter>
        <Button variant="ghost" class="rounded-xl px-3 py-1.5 text-sm text-text-secondary hover:bg-surface-2" @click="close">
          取消
        </Button>
        <Button class="rounded-xl bg-accent-500 px-3 py-1.5 text-sm text-white hover:bg-accent-600" :disabled="isSubmitting" @click="handleConfirm">
          {{ isSubmitting ? '创建中...' : '创建' }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// packages/web/src/overlays/dialogs/CreateFolderDialog.tsx
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

interface CreateFolderDialogProps {
  onClose?: (result?: unknown) => void
  onConfirm?: (name: string) => void | Promise<void>
}

export default function CreateFolderDialog({ onClose, onConfirm }: CreateFolderDialogProps) {
  const [name, setName] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [isSubmitting, setIsSubmitting] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError(null)

    const trimmed = name.trim()
    if (!trimmed) {
      setError('文件夹名称不能为空')
      return
    }

    setIsSubmitting(true)
    try {
      await onConfirm?.(trimmed)
      onClose?.(true)
    } catch (err: unknown) {
      const message = (err as { message?: string })?.message
      setError(message || '创建失败')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <Dialog open onOpenChange={() => onClose?.(false)}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>新建文件夹</DialogTitle>
          <DialogDescription>输入文件夹名称，在当前目录创建新文件夹。</DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor="folder-name">名称</Label>
            <Input
              id="folder-name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="文件夹名称"
              autoFocus
              aria-invalid={!!error}
            />
            {error && <p className="text-xs text-destructive">{error}</p>}
          </div>

          <div className="flex justify-end gap-2 pt-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => onClose?.(false)}
              disabled={isSubmitting}
            >
              取消
            </Button>
            <Button type="submit" disabled={isSubmitting}>
              {isSubmitting ? '创建中...' : '创建'}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  )
}
