// packages/web/src/components/kb/BreadcrumbNav.tsx
import { Home, ChevronRight } from 'lucide-react'
import type { Folder } from '@/stores/file'

interface BreadcrumbNavProps {
  items: Folder[]
  currentKbName: string
  onNavigate: (folderId: string | null) => void
}

export function BreadcrumbNav({ items, currentKbName, onNavigate }: BreadcrumbNavProps) {
  const isLast = (index: number) => index === items.length - 1

  return (
    <nav className="flex items-center gap-1 text-sm" aria-label="目录导航">
      <button
        type="button"
        data-testid="breadcrumb-root"
        className="flex items-center gap-1 text-text-secondary hover:text-text-primary transition-colors"
        onClick={() => onNavigate(null)}
        aria-label="返回根目录"
      >
        <Home className="h-4 w-4" />
        <span>{currentKbName}</span>
      </button>

      {items.map((folder, index) => (
        <span key={folder.id} className="flex items-center gap-1">
          <ChevronRight data-testid="breadcrumb-separator" className="h-3 w-3 text-text-tertiary" />
          {isLast(index) ? (
            <span className="text-text-primary font-medium" aria-current="page">
              {folder.name}
            </span>
          ) : (
            <button
              type="button"
              className="text-text-secondary hover:text-text-primary transition-colors"
              onClick={() => onNavigate(folder.id)}
            >
              {folder.name}
            </button>
          )}
        </span>
      ))}
    </nav>
  )
}

// packages/webui/src/components/knowledge-base/BreadcrumbNav.vue
<script setup lang="ts">
import { ChevronRightIcon, HomeIcon } from 'lucide-vue-next'
import type { Folder } from '@/stores/file'

const props = defineProps<{
  path: Folder[]
}>()

const emit = defineEmits<{
  navigate: [folderId: string | null]
}>()
</script>

<template>
  <nav class="flex items-center gap-1 text-sm text-text-secondary">
    <button
      class="flex items-center gap-1 rounded-lg px-2 py-1 hover:bg-surface-2 hover:text-text-primary"
      @click="emit('navigate', null)"
    >
      <HomeIcon class="size-4" />
      <span>根目录</span>
    </button>
    <template v-for="(folder, idx) in props.path" :key="folder.id">
      <ChevronRightIcon class="size-4 text-text-tertiary" />
      <button
        class="rounded-lg px-2 py-1 hover:bg-surface-2 hover:text-text-primary"
        @click="emit('navigate', folder.id)"
      >
        {{ folder.name }}
      </button>
    </template>
  </nav>
</template>
