// packages/web/src/components/chat/KbSelector.tsx
import { useState, useRef, useEffect, useCallback } from 'react'
import { useRequest } from 'alova/client'
import { getKbList } from '@/api/kb'
import type { KbEntry } from '@goferbot/data'
import { DatabaseIcon, HashIcon } from 'lucide-react'
import { cn } from '@/utils/cn'

interface KbSelectorProps {
  selectedIds: string[]
  onToggle: (kbId: string) => void
  disabled?: boolean
}

export function KbSelector({ selectedIds, onToggle, disabled = false }: KbSelectorProps) {
  const [open, setOpen] = useState(false)
  const containerRef = useRef<HTMLDivElement>(null)

  const { data, loading, error, send } = useRequest(
    () => getKbList(),
    { immediate: false },
  )

  const rawData = (data as any)
  const kbList: KbEntry[] = Array.isArray(rawData) ? rawData : (rawData?.data ?? [])

  const handleOpen = useCallback(() => {
    if (disabled) return
    setOpen(true)
    if (!data && !loading) send()
  }, [disabled, data, loading, send])

  const handleClose = useCallback(() => setOpen(false), [])

  useEffect(() => {
    if (!open) return
    function onMouseDown(e: MouseEvent) {
      if (
        containerRef.current &&
        !containerRef.current.contains(e.target as Node)
      ) {
        handleClose()
      }
    }
    document.addEventListener('mousedown', onMouseDown)
    return () => document.removeEventListener('mousedown', onMouseDown)
  }, [open, handleClose])

  useEffect(() => {
    if (!open) return
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') handleClose()
    }
    document.addEventListener('keydown', onKeyDown)
    return () => document.removeEventListener('keydown', onKeyDown)
  }, [open, handleClose])

  return (
    <div ref={containerRef} className="relative">
      <button
        type="button"
        data-testid="kb-selector-trigger"
        onClick={handleOpen}
        disabled={disabled}
        className={cn(
          'inline-flex items-center gap-1 rounded px-2 py-0.5 text-xs',
          'text-text-secondary hover:bg-surface-2 hover:text-text-primary',
          'disabled:cursor-not-allowed disabled:opacity-50',
        )}
      >
        <HashIcon className="size-3.5" />
        <span>知识库</span>
        {selectedIds.length > 0 && (
          <span className="ml-0.5 rounded-full bg-brand-primary px-1.5 py-px text-[10px] text-white">
            {selectedIds.length}
          </span>
        )}
      </button>

      {open && (
        <div
          data-testid="kb-selector-dropdown"
          className="absolute bottom-full left-0 mb-2 max-h-48 w-72 overflow-y-auto rounded-xl border border-border-default bg-white shadow-xl"
        >
          {loading && (
            <div className="space-y-2 p-3">
              {[1, 2, 3].map((i) => (
                <div key={i} className="h-8 w-full animate-pulse rounded bg-surface-2" />
              ))}
            </div>
          )}

          {!loading && error && (
            <div className="space-y-2 p-4 text-center text-sm">
              <p className="text-text-secondary">{error.message ?? '加载失败'}</p>
              <button
                data-testid="kb-selector-retry"
                className="text-brand-primary hover:underline"
                onClick={() => send()}
              >
                重试
              </button>
            </div>
          )}

          {!loading && !error && kbList.length === 0 && (
            <div className="p-4 text-center text-sm text-text-secondary">
              请先创建知识库
            </div>
          )}

          {!loading && !error && kbList.map((kb) => (
            <div
              key={kb.id}
              data-testid="kb-selector-item"
              className={cn(
                'flex cursor-pointer items-center gap-2 px-3 py-2 text-sm transition-colors',
                'text-text-primary hover:bg-surface-2',
              )}
              onClick={(e) => {
                e.preventDefault()
                onToggle(kb.id)
              }}
            >
              <input
                type="checkbox"
                checked={selectedIds.includes(kb.id)}
                className="pointer-events-none size-4 rounded border-border-default text-brand-primary focus:ring-brand-primary"
                readOnly
              />
              <DatabaseIcon className="size-4 text-text-secondary" />
              <span className="truncate">{kb.name}</span>
              <span className="ml-auto text-xs text-text-tertiary">
                {kb.fileCount ?? 0} 文档
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

// packages/webui/src/components/chat/KbSelector.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { KnowledgeBase } from '@/types'
import { DatabaseIcon } from 'lucide-vue-next'
import { Skeleton } from '@/components/ui/skeleton'

const props = defineProps<{
  knowledgeBases: KnowledgeBase[]
  selectedIds: string[]
  visible: boolean
  loading?: boolean
  error?: string | null
}>()

const emit = defineEmits<{
  select: [kb: KnowledgeBase]
  unselect: [kbId: string]
  close: []
  retry: []
}>()

const selectedIndex = ref(0)

const filtered = computed(() => {
  return props.knowledgeBases
})

watch(() => filtered.value.length, () => {
  selectedIndex.value = 0
})

watch(() => props.visible, (v) => {
  if (v) selectedIndex.value = 0
})

function toggleKb(kb: KnowledgeBase) {
  if (props.selectedIds.includes(kb.id)) {
    emit('unselect', kb.id)
  } else {
    emit('select', kb)
  }
}

function handleKeydown(e: KeyboardEvent) {
  if (!props.visible) return
  if (e.key === 'ArrowDown') {
    e.preventDefault()
    selectedIndex.value = (selectedIndex.value + 1) % filtered.value.length
  } else if (e.key === 'ArrowUp') {
    e.preventDefault()
    selectedIndex.value = (selectedIndex.value - 1 + filtered.value.length) % filtered.value.length
  } else if (e.key === 'Enter') {
    e.preventDefault()
    const kb = filtered.value[selectedIndex.value]
    if (kb) toggleKb(kb)
  } else if (e.key === 'Escape') {
    emit('close')
  }
}

defineExpose({ handleKeydown })
</script>

<template>
  <div
    v-if="visible"
    data-testid="kb-selector-dropdown"
    class="absolute bottom-full left-0 mb-2 max-h-48 w-72 overflow-y-auto rounded-xl border border-border-default bg-white shadow-xl"
  >
    <div v-if="loading" class="space-y-2 p-3">
      <Skeleton v-for="i in 3" :key="i" class="h-8 w-full" />
    </div>
    <div v-else-if="error" class="space-y-2 p-4 text-center text-sm">
      <p class="text-text-secondary">{{ error }}</p>
      <button
        data-testid="kb-selector-retry"
        class="text-accent-500 hover:underline"
        @click="$emit('retry')"
      >
        重试
      </button>
    </div>
    <div v-else-if="knowledgeBases.length === 0" class="p-4 text-center text-sm text-text-secondary">
      请先创建知识库
    </div>
    <div
      v-for="(kb, i) in filtered"
      :key="kb.id"
      data-testid="kb-selector-item"
      :class="[
        'flex cursor-pointer items-center gap-2 px-3 py-2 text-sm transition-colors',
        i === selectedIndex ? 'bg-accent-soft text-accent-500' : 'text-text-primary hover:bg-surface-2',
      ]"
      @mousedown.prevent="toggleKb(kb)"
    >
      <input
        type="checkbox"
        :checked="selectedIds.includes(kb.id)"
        class="pointer-events-none size-4 rounded border-border-default text-accent-500 focus:ring-accent-500"
        readonly
      />
      <DatabaseIcon class="size-4 text-text-secondary" />
      <span class="truncate">{{ kb.name }}</span>
      <span class="ml-auto text-xs text-text-tertiary">{{ kb.documentCount || 0 }} 文档</span>
    </div>
  </div>
</template>
